== Toolchain

The toolchain is the set of software tools that will be used to develop robotics software that run on the different platforms (Arduino, Raspberry PI, PC, ...)

=== Overal design goals

* Easy to setup, even by less experienced programmers
* Less is more when it comes to dependencies

=== C++

This is the language of the future, especially when it comes to kicking the most juice out of a CPU. The latest http://en.wikipedia.org/wiki/C%2B%2B11[C\{++}11 standard] is currently supported very well by the latest http://gcc.gnu.org[g++] compiler, which can even be used to program an 8-bit Arduino.

=== Asciidoc

http://www.methods.co.nz/asciidoc/[Asciidoc] is the markup language that we use to document all our experiments. https://github.com/github/gollum[Gollum] is used to create the pages in a http://git-scm.com/[git] respository, and these pages are also converted into a static website using an in-house developed http://ruby-lang.org[ruby] script that uses the _asciidoc_ program to convert these pages into HTML. So, asciidoc is not only a markup language, but also comes with a toolchain to manipulate and convert these documents.